//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Runtime.Serialization.Json;
    using System.Text;
    using Newtonsoft.Json.Linq;

    public partial class StoreOwner : ISerializable
    {
        public int id { get; set; }
        public string email { get; set; }
    
        public virtual User User { get; set; }

        public void Serialize(JObject userInfo)
        {
            this.email =(string) userInfo["email"];
            this.email = this.email.Trim();



        }
    }
}
